name = "micro-pd-pilot"
main = "src/index.ts"
compatibility_date = "2026-04-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "micro-pd-pilot"
database_id = "3817d1f0-7999-4cec-8a83-c78a5ff4b40f"

[vars]
APP_NAME = "micro-pd-pilot"
SCHEDULER_TIMEZONE = "America/Chicago"
SCHEDULER_SEND_DAYS = "Monday,Wednesday"
SCHEDULER_SEND_HOUR = "14"
SCHEDULER_SEND_MINUTE = "25"
DEFAULT_PILOT_GROUP = "cohort_1"

[triggers]
crons = ["*/5 * * * *"]
